apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-blue
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/muralikrishna-sunkara/k8s-argocd-blue-gree.git
    targetRevision: main
    path: apps/sample-app-blue
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  
  revisionHistoryLimit: 10