apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-blue
  namespace: default
  labels:
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
      version: blue
  template:
    metadata:
      labels:
        app: sample-app
        version: blue
    spec:
      containers:
      - name: sample-app-blue
        image: nginx:1.21-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: APP_VERSION
          value: "v1.0-Blue"
        - name: APP_ENV
          value: "production"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3