apiVersion: v1
kind: Service
metadata:
  name: sample-app-blue
  namespace: default
  labels:
    app: sample-app
    version: blue
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: sample-app
    version: blue