apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-green
  namespace: default
  labels:
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
      version: green
  template:
    metadata:
      labels:
        app: sample-app
        version: green
    spec:
      containers:
      - name: sample-app-green
        image: nginx:1.25-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: APP_VERSION
          value: "v2.0-Green"
        - name: APP_ENV
          value: "staging"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3